import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  page: {
    padding: 20,
    margin: '0 auto',
    color: '#e5e7eb',
    background: '#0b1220',
    minHeight: '100vh',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 16,
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  title: {
    fontSize: 22,
    fontWeight: 800,
    lineHeight: 1.2,
  },
  subTitle: {
    marginTop: 6,
    fontSize: 13,
    opacity: 0.85,
    color: '#cbd5e1',
  },
  actions: {
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  button: {
    padding: '10px 14px',
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'rgba(148,163,184,0.28)',
    background: 'rgba(15,23,42,0.55)',
    color: '#e5e7eb',
    cursor: 'pointer',
    fontWeight: 700,
    letterSpacing: '-0.01em',
  },
  buttonPrimary: {
    background: '#2563eb',
    borderColor: '#2563eb',
  },
  buttonDanger: {
    background: '#dc2626',
    borderColor: '#dc2626',
  },
  buttonGhost: {
    background: 'rgba(15,23,42,0.35)',
  },
  buttonDisabled: {
    opacity: 0.55,
    cursor: 'not-allowed',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 12,
  },
  card: {
    border: '1px solid rgba(148,163,184,0.18)',
    background: 'rgba(15,23,42,0.45)',
    borderRadius: 14,
    padding: 14,
    boxShadow: '0 8px 30px rgba(0,0,0,0.18)',
  },
  fullWidth: {
    gridColumn: '1 / -1',
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: 800,
    marginBottom: 12,
  },
  subCardTitle: {
    fontSize: 13,
    fontWeight: 800,
    marginTop: 14,
    marginBottom: 8,
    opacity: 0.95,
    color: '#e2e8f0',
  },
  presetGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 8,
    marginBottom: 10,
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 10,
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    fontSize: 12,
    opacity: 0.95,
    color: '#cbd5e1',
  },
  input: {
    padding: '10px 10px',
    borderRadius: 10,
    border: '1px solid rgba(148,163,184,0.22)',
    background: 'rgba(2,6,23,0.55)',
    color: '#e5e7eb',
    outline: 'none',
  },
  checkboxCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    justifyContent: 'flex-end',
  },
  checkboxLabel: {
    display: 'flex',
    gap: 8,
    alignItems: 'center',
    fontSize: 12,
    color: '#cbd5e1',
  },
  hint: {
    marginTop: 12,
    fontSize: 12,
    opacity: 0.85,
    lineHeight: 1.55,
    color: '#94a3b8',
  },
  writeRow: {
    display: 'grid',
    gridTemplateColumns: '240px 1fr 1fr',
    gap: 10,
    marginTop: 10,
    alignItems: 'end',
  },
  hintSmall: {
    fontSize: 12,
    opacity: 0.85,
    lineHeight: 1.4,
    color: '#94a3b8',
  },
  healthBox: {
    borderRadius: 12,
    border: '1px solid rgba(148,163,184,0.18)',
    padding: 12,
  },
  healthGood: {
    background: 'rgba(34,197,94,0.10)',
    borderColor: 'rgba(34,197,94,0.28)',
  },
  healthWarn: {
    background: 'rgba(234,179,8,0.10)',
    borderColor: 'rgba(234,179,8,0.28)',
  },
  healthBad: {
    background: 'rgba(239,68,68,0.10)',
    borderColor: 'rgba(239,68,68,0.28)',
  },
  healthTitleRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  healthTitle: {
    fontSize: 14,
    fontWeight: 900,
  },
  healthBadge: {
    fontSize: 12,
    fontWeight: 900,
    opacity: 0.95,
  },
  healthDetail: {
    marginTop: 8,
    fontSize: 12,
    opacity: 0.9,
    lineHeight: 1.55,
  },
  testUsersSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTop: '1px solid rgba(148,163,184,0.14)',
  },
  testUsersTitle: {
    fontSize: 13,
    fontWeight: 900,
    marginBottom: 8,
  },
  testUsersActions: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  },
  testUsersStatus: {
    marginTop: 8,
    fontSize: 12,
  },
  kvGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 10,
  },
  k: {
    fontSize: 11,
    opacity: 0.8,
    color: '#94a3b8',
  },
  v: {
    fontSize: 16,
    fontWeight: 900,
  },
  vSmall: {
    fontSize: 12,
    fontWeight: 600,
    opacity: 0.95,
    wordBreak: 'break-word',
    color: '#cbd5e1',
  },
  opRow: {
    borderTop: '1px solid rgba(148,163,184,0.14)',
    paddingTop: 10,
    marginTop: 10,
  },
  opName: {
    fontSize: 13,
    fontWeight: 900,
    marginBottom: 8,
  },
  opMetrics: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gap: 10,
  },
  opLastError: {
    marginTop: 8,
    fontSize: 12,
    opacity: 0.85,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  logBox: {
    borderRadius: 12,
    border: '1px solid rgba(148,163,184,0.16)',
    background: 'rgba(2,6,23,0.55)',
    padding: 10,
    minHeight: 220,
    maxHeight: 420,
    overflow: 'auto',
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 12,
  },
  logEmpty: {
    opacity: 0.7,
    color: '#94a3b8',
  },
  logRow: {
    display: 'grid',
    gridTemplateColumns: '78px 100px 60px 70px 1fr',
    gap: 10,
    alignItems: 'center',
    padding: '6px 0',
    borderBottom: '1px solid rgba(148,163,184,0.12)',
  },
  logAt: { opacity: 0.9 },
  logOp: { opacity: 0.95 },
  logOk: { color: '#22c55e', fontWeight: 900 },
  logErr: { color: '#ef4444', fontWeight: 900 },
  logMs: { opacity: 0.95 },
  logMsg: {
    opacity: 0.9,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
};
